### ISSUE TITLE
"Loading available logins..." get's stuck.

### ISSUE THREAD

**Issue by hmoenck** [browserpass/browserpass-extension#138]
### General information

-   Operating system + version: Windows Server 2019 Standard Edition, Version 1809
-   Browser + version: Firefox Quantum 66.0.3 (64-Bit)
-   Information about the host app:
    -   Host app installed via MSI (3.0.6)
-   Information about the browser extension:
    -   Installed via addons.mozilla.org
    -   Browserpass extension version as reported by your browser: 3.1.1
- Using gpg/smartcard for pw decryption

### The Issue
Reproduce:
1. Browse for a while (exact cause unknown)

When using the key combination ctrl+shift+L the popup appears and only shows "Loading available logins..." forever. It seems stuck and will happen from then on on every page. Restarting firefox solves the issue for a while.  
I tried a few things to reproduce it, but it seems pretty random so far. I'll update if new info comes up.

**Comment by maximbaz** [comment]
Hmm, interesting, please do let me know if you find a reliable way to reproduce this.

**Comment by iquiw** [comment]
I've got similar issue several times. There are too many `browserpass-windows64.exe` processes on Task Manager when it happens.

![image](https://user-images.githubusercontent.com/238681/59906132-ea3b0680-9442-11e9-99ac-9ccab14659a3.png)

I don't know how it can be reproduced though, sorry.

I like this extension anyway, thanks!

**Comment by maximbaz** [comment]
I believe this has been fixed in `3.2.2`, please do let me know if you still experience the issue.

**Comment by iquiw** [comment]
@maximbaz Thank you for the work.
Unfortunately, I am still seeing the many processes issue. (Now I don't see "Loading available logins..." message possibly because of the fix)

I think I found the trigger action. It is "Undo Close Tab".

Steps:
1. Start Firefox.
2. Open several tabs and close one.
3. Wait 1 minute (for cache expire I suppose)
4. Undo Close Tab.

Then multiple `browserpass-windows64.exe` processes are executed.
Sometimes the processes exit soon, but sometimes they remain and cause high CPU usage of Firefox.

**Comment by maximbaz** [comment]
Reopening to remember to try to reproduce.

> (Now I don't see "Loading available logins..." message possibly because of the fix)

Could you confirm please that the actual bug is fixed now, the extension is working as expected at all times, but the only annoying part is that sometimes there's a spike in CPU usage?

**Comment by erayd** [comment]
@Maximbaz I don't consider it fixed, when the user is still encountering this:

> Unfortunately, I am still seeing the many processes issue.

**Comment by iquiw** [comment]
Once the many processes issue happens, eventually, it causes Firefox crash.

I'm inclined to suspect it is Firefox's bug. I will check other extension with host application if I have time.

**Comment by erayd** [comment]
@iquiw My concern is that those host processes should be exiting almost immediately after being spawned; they shouldn't hang around like that.

Are you able to check how long those many processes are persisting for?

**Comment by iquiw** [comment]
When the problem does not happen, they exit immediately.
When the problem happens, they never exit at least within about 30 minutes.

> (Now I don't see "Loading available logins..." message possibly because of the fix)

The above was wrong, sorry. It is displayed when the icon is clicked and number of process is increased by the click.

**Comment by erayd** [comment]
> When the problem happens, they never exit at least within about 30 minutes.

@iquiw Do they use any CPU or disk I/O while hanging there?

**Comment by iquiw** [comment]
`browserpass-windows64.exe` does not consume CPU and memory as in https://github.com/browserpass/browserpass-extension/issues/138#issuecomment-504328229. One of Firefox processes consumes CPU, not sure about memory.
After closing Firefox window, all `browserpass-windows64.exe` processes exit but the Firefox process remains with high CPU.

**Comment by iquiw** [comment]
Interestingly, I could not reproduce the problem on master (025adf2e50b30ccdc91f3926e5a8bf5616bc69cd).

Maybe, this commit (3a2af64bc3b55c771bfd30c5ee39a149c3fac0ad) fixed the problem, or reduced the occurrence a lot.

This issue could be closed by next release, IMHO.

**Comment by erayd** [comment]
@iquiw That commit is directly intended to address this issue - thought it was already in a release sorry! Thanks for pointing out that it isn't.

**Comment by maximbaz** [comment]
Wow, it was not as "small refactoring" as I expected - thanks for helping us figure this out! I've just released `3.2.3` from the latest master 👍
